### ISSUE TITLE
關於SDK載入Visual Studio 2017版本

### ISSUE THREAD

**Issue by namuhevil** [Shining3D/2XSDK#14]
I want to ask some questions about Visual Studio 2017.
We already buy your devices, but we can not do the real time scan from SDK now.
首先，不知道可否給我們該怎麼引入你們SDK的方式。舉例來說：
1.  點選專案屬性
2. 進入C/C++
3. 其他include目錄 
等等，該引入甚麼檔案方便給我們嗎? 因為我們要做更進一步的實驗及研究，未來將會發表在ieee國際研討會中。謝謝。

**Comment by namuhevil** [comment]
亦或者方便給我們整個專案，讓我們可以直接開啟並且更改內部的程式達到我們想要做的研究。

**Comment by namuhevil** [comment]
這是我的聯絡方式。carlosstarw@gmail.com，微信：hondada_HD

**Comment by cjmdaixi** [comment]
Hi,

As we explained in SDKDoc(https://github.com/Shining3D/SDKDoc), the integration of our 2XSDK is not like a normal 3rd party library. There are NO .h or .lib files any more. Instead, your app could talk to our SDK, which is now a standalone executable, via ZMQ and shared memory.

There are three ready-for-testing demos on our official GitHub site.

Best,
Jinming Chen
